name: Build and Deploy API

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host a known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Preparar y copiar archivos
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            mkdir -p /var/www/toros-api.salazarcode.net
            chmod 755 /var/www/toros-api.salazarcode.net
          '
          rsync -avz --delete ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/toros-api.salazarcode.net/

      - name: Build y Deploy Docker
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            cd /var/www/toros-api.salazarcode.net &&
            docker build -t toros-api . &&
            docker stop toros-api || true &&
            docker rm toros-api || true &&
            docker run -d \
              --name toros-api \
              --network eventmanager_network \
              -p 5000:80 \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e ASPNETCORE_URLS="http://+:80" \
              --restart always \
              toros-api
          '

      - name: Limpiar imágenes antiguas
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'docker system prune -f'
